language: php
matrix:
  include:
  - php: 5.4
  - php: 5.5
  - php: hhvm
install:
- composer install --dev
script:
- "./vendor/bin/phpunit"
after_script:
- "./vendor/bin/phpcs --config-set installed_paths ../../wp-coding-standards/wpcs"
- "./vendor/bin/phpcs . -p -s -v -n --standard=./codesniffer.xml --extensions=php"
- "./vendor/bin/test-reporter"
env:
  global:
    secure: iYWazyvp/sBhqW4GMiOrPHXrUQTGVVNIPVTUU3mSvRmFSEvZRbL0NbfFEUJhfqNITrEoPxQxoDaf6MJ9UNPqfcARuChrUybHKFv9Ouvd05kmH4vwPJroJdl3iawQzeZBXpxg/Wn8ciW79bVuCH2/LMZWk1bcKS87VbjG6CwUF8s=
