language: php
matrix:
  include:
    - php: 5.4
      env: PHPLINT=1
    - php: 5.5
    - php: hhvm
before_script:
  - PLUGIN_SLUG=$(basename $(pwd))
  - git clone https://github.com/squizlabs/PHP_CodeSniffer.git phpcs
  - git clone https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards.git wpcs
  - scripts/phpcs --config-set installed_paths scripts/wpcs

script:
  - if [[ "$PHPLINT" == "1" ]]; then scripts/phpcs -p -s -v -n . --standard=./codesniffer.xml --extensions=php; fi
