language: php
matrix:
  include:
  - php: 5.4
  - php: 5.5
  - php: hhvm
install:
- composer install --dev
- git clone https://github.com/squizlabs/PHP_CodeSniffer.git ~/phpcs
- git clone https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards.git
  ~/wpcs
- "~/phpcs/scripts/phpcs --config-set installed_paths ~/wpcs"
script:
- "./vendor/bin/phpunit"
after_script:
- "./vendor/bin/test-reporter"
- "~/phpcs/scripts/phpcs . -p -s -v -n --standard=./codesniffer.xml --extensions=php"
env:
  global:
    secure: iYWazyvp/sBhqW4GMiOrPHXrUQTGVVNIPVTUU3mSvRmFSEvZRbL0NbfFEUJhfqNITrEoPxQxoDaf6MJ9UNPqfcARuChrUybHKFv9Ouvd05kmH4vwPJroJdl3iawQzeZBXpxg/Wn8ciW79bVuCH2/LMZWk1bcKS87VbjG6CwUF8s=
