language: php
matrix:
  include:
  - php: 5.4
  - php: 5.5
  - php: hhvm
install:
- composer install --dev
before_script:
- REPO_DIR=$(pwd)
script:
- "./vendor/bin/phpunit"
- "if [ $TRAVIS_PHP_VERSION == "hhvm" ]; then ./vendor/bin/phpcs --config-set installed_paths $REPO_DIR/vendor/wp-coding-standards/wpcs; fi"
- "if [ $TRAVIS_PHP_VERSION == "hhvm" ]; then ./vendor/bin/phpcs . -p -s -v -n --standard=./codesniffer.xml --extensions=php; fi"
- "if [ $TRAVIS_PHP_VERSION == "hhvm" ]; then ./vendor/bin/test-reporter; fi"
env:
  global:
    secure: iYWazyvp/sBhqW4GMiOrPHXrUQTGVVNIPVTUU3mSvRmFSEvZRbL0NbfFEUJhfqNITrEoPxQxoDaf6MJ9UNPqfcARuChrUybHKFv9Ouvd05kmH4vwPJroJdl3iawQzeZBXpxg/Wn8ciW79bVuCH2/LMZWk1bcKS87VbjG6CwUF8s=
