language: php
matrix:
  include:
  - php: 5.4
  - php: 5.5
    env: PHPLINT=1
  - php: hhvm
install:
- composer selfupdate --no-interaction
- composer install --no-interaction
script:
- composer run-script test
- if [[ "$PHPLINT" == "1" ]]; then composer run-script check-codestyle; fi
env:
  global:
    secure: iYWazyvp/sBhqW4GMiOrPHXrUQTGVVNIPVTUU3mSvRmFSEvZRbL0NbfFEUJhfqNITrEoPxQxoDaf6MJ9UNPqfcARuChrUybHKFv9Ouvd05kmH4vwPJroJdl3iawQzeZBXpxg/Wn8ciW79bVuCH2/LMZWk1bcKS87VbjG6CwUF8s=
